FROM alpine

RUN apk update && \
    apk --no-cache --update add bash ncurses-libs openssl && \
    rm -rf /var/cache/apk/*

EXPOSE 4000

ARG app_name
ENV APP=${app_name} PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

RUN mkdir -p /app
ADD $APP.tar.gz /app
RUN ln -s /app/bin/$APP /app/bin/elixir-application

ENTRYPOINT ["/app/bin/elixir-application"]
