FROM alpine

RUN apk update && \
    apk --no-cache --update add bash ncurses-libs openssl && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD api.tar.gz ./

ENTRYPOINT ["/bin/api"]
