FROM elixir:1.6.3-alpine

ENV HOME=/opt/app/ TERM=xterm

RUN apk update
RUN apk --no-cache --update add git 

ENV REPLACE_OS_VARS=true

# Install Hex+Rebar
RUN mix local.hex --force && \
    mix local.rebar --force

WORKDIR /opt/app
ENV MIX_ENV=prod
COPY . .
RUN mix release --env=prod --verbose
